### PR TITLE
Populate more ideas for the demo app

### PR DESCRIPTION
**Pull request by dmitryvlass**
### Description

I added a couple of "creative" examples which would inspire users for their generation.

### CODE REVIEW

**Review by callumflack — COMMENTED** [review]
Let's use Matthias' prompts in [VAN-491](https://linear.app/vana-team/issue/VAN-491/list-of-example-prompts-to-inspire-users)

**Review by callumflack — APPROVED** [review]
@dmitryvlass approving this now so we can merge it tomorrow morning

**Comment by tnunamak** [comment]
Thoughts on linking to https://prompthero.com or similar resources?

**Comment by dmitryvlass** [comment]
It has been done here: https://github.com/corsali/vana-portrait-demo/pull/18

Closed.

**Pull request closed without merging**
